//! @arch:layer(kg)
//! @arch:role(protocol)
//!
//! Agent runtime vocabulary — `SessionId`, `AgentEvent`, conversation
//! `Message`s — shared by every runner backend.
//!
//! ## Why this is in `yah-kg`
//!
//! `yah-kg` is the contract crate. The agent runtime has two runners:
//! the Claude Agent SDK pane (R028 — Tauri host) and yah-runner (R018 —
//! provider trait + non-Claude backends). Both consume the same
//! [`crate::prelude::Prelude`] and emit the same [`AgentEvent`] stream;
//! sharing those types here is the clean way to keep them from drifting.
//!
//! ## What's intentionally not here
//!
//! - **Rig identity** — `RigId` lives in the Tauri host (`AppState`).
//!   When the Tauri layer needs to fan an `AgentEvent` out to the
//!   renderer it wraps with a rig-tagged envelope (mirrors the
//!   `RigEvent` wrapper around `ArchEvent`). The runtime types
//!   themselves stay runner-agnostic.
//! - **History storage** — R018-T1 owns the session JSONL format. This
//!   module just defines the in-memory `Message` shape that runners
//!   maintain per turn.
//! - **Tool use** — Anthropic's tool-use loop and yah-runner's MCP
//!   bridge will both need `ToolCall` / `ToolResult` variants on
//!   `AgentEvent`. Adding them is non-breaking (serde tagged-union
//!   forward-compat); leave the slot until either runner has a concrete
//!   use case.

use serde::{Deserialize, Serialize};

/// Stable id for an agent session. Format: `session:<8 hex>` (the
/// Tauri host mints these via `blake3(now_ms || counter)`; other
/// runners pick whatever scheme they like — the contract is just
/// "stable string, unique within the host process").
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub String);

impl SessionId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// One conversation turn. The Anthropic API distinguishes only `user`
/// and `assistant`; system content rides on the prelude (cached prefix)
/// so it isn't stored in the message history.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    pub role: Role,
    pub content: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User,
    Assistant,
}

/// Token-counting snapshot for one turn, surfaced on
/// [`AgentEvent::TurnEnded`] so the UI can render per-pane cost gauges
/// (input / output / cache-read / cache-creation) and a thinking-budget
/// consumption bar.
///
/// All four fields are wire-shaped after Anthropic's `/v1/messages`
/// usage object (the richest of the three runtime cells we serve);
/// runners that don't surface every field set the missing ones to
/// `None`. Specifically:
///
/// - **HA-family** (`anthropic`, `crab`) — fills every field; Anthropic
///   emits all four numbers.
/// - **PVd** (`claude-cli` subprocess) — fills every field too;
///   claude's `result.usage` is the same shape as the API's.
/// - **HO-family** (`openai`, `ollama`) — fills `input_tokens` and
///   `output_tokens` only; OpenAI's wire doesn't expose cache numbers.
///   Ollama Cloud may surface cache fields in the future; the slot is
///   already here for it.
///
/// `thinking_tokens` is the subset of `output_tokens` spent on
/// extended-thinking content blocks. `None` when the turn didn't have
/// thinking enabled or the runtime can't separate them (most providers
/// today). Filling this on the HA path requires summing token counts
/// across `thinking` content blocks specifically — deferred to a
/// follow-up since it needs the per-block streaming machinery.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct TurnUsage {
    /// Total input tokens charged for this turn (including the cached
    /// prefix — Anthropic bills cache reads at ~10% of full input
    /// pricing but counts them in this number too).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<u32>,
    /// Output tokens generated by the model. Includes thinking tokens
    /// when `thinking_tokens` is `Some(_)`; the renderer subtracts to
    /// show "answer tokens" vs "thinking tokens".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<u32>,
    /// Subset of `input_tokens` that hit the prompt cache. Cache hits
    /// bill at ~10% on Anthropic; surfacing this is what makes the
    /// "cache hit ratio" gauge in the UI work.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u32>,
    /// Tokens spent populating the cache (one-time cost on the first
    /// turn of a session; ~0 on subsequent turns of a stable prelude).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u32>,
    /// Tokens spent inside extended-thinking content blocks. Subset of
    /// `output_tokens`. `None` when the runtime can't separate them.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_tokens: Option<u32>,
}

/// Wire shape for streamed events. `sessionId` is always present so the
/// renderer / non-renderer subscriber can route by session without
/// inspecting the kind tag.
///
/// Non-breaking evolution: add new variants at the tail. Renderers
/// match the variants they care about and ignore the rest.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AgentEvent {
    /// Session opened. Carries the assembled prelude's cache key + ring
    /// depth so the UI can show the budget gauge before the first turn.
    /// Engine is the canonical `provider:model` form (e.g.
    /// `claude:opus-4-7`, `openai:gpt-5`).
    SessionStarted {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        #[serde(rename = "ticketId")]
        ticket_id: String,
        engine: String,
        #[serde(rename = "cacheKey")]
        cache_key: String,
        #[serde(rename = "estimatedTokens")]
        estimated_tokens: u32,
        #[serde(rename = "ringDepth")]
        ring_depth: f32,
    },
    /// Turn started. Renderer flips the pane to "thinking…" until the
    /// first `MessageDelta` arrives.
    TurnStarted {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
    },
    /// Streaming text delta from the assistant. `text` is whatever the
    /// upstream emitted in this SSE chunk; the renderer concatenates.
    MessageDelta {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        text: String,
    },
    /// Turn finished cleanly. `text` is the full assistant response —
    /// useful for callers that don't want to fold deltas client-side
    /// (snapshot tests, the CLAUDE.md generator).
    ///
    /// `usage` is the per-turn token-counting snapshot when the
    /// runtime cell could surface one (HA-family + PVd today, HO
    /// once `stream_options.include_usage` lands). `None` for chat
    /// sessions on backends that don't emit a usage frame.
    TurnEnded {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        text: String,
        #[serde(rename = "stopReason", skip_serializing_if = "Option::is_none")]
        stop_reason: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        usage: Option<TurnUsage>,
    },
    /// Turn aborted mid-stream. Symmetric to [`Self::TurnEnded`]: every
    /// `Runner::send` produces exactly one terminal turn event, success
    /// or failure. `text` carries whatever the runner accumulated before
    /// the failure (empty `String` if the failure was pre-stream); the
    /// session log persists this instead of every `MessageDelta`, so
    /// replay reconstructs the partial reply without N×K-byte JSONL
    /// overhead. `message` is the human-readable failure reason.
    ///
    /// Distinct from [`Self::Error`]: that variant is for synchronous,
    /// command-shaped failures (keychain-missing, runner-not-configured)
    /// where there is no accumulated text to flush. In-stream failures
    /// from a live turn always emit `TurnFailed`.
    TurnFailed {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        text: String,
        message: String,
    },
    /// Session closed (manually via stop or implicitly by an
    /// unrecoverable error). After this the renderer should drop the
    /// pane's session reference.
    SessionEnded {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
    },
    /// Synchronous, command-shaped failure with no in-flight turn —
    /// e.g. keychain-missing, runner-not-found, malformed engine
    /// string. Distinct from [`Self::TurnFailed`] (which represents an
    /// aborted live turn carrying partial accumulated text). Renderer
    /// surfaces as a toast + inline error block; the session itself
    /// stays open so the user can retry without re-paying the prelude
    /// assembly cost.
    Error {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        message: String,
    },
    /// Provider asked us to invoke a tool. Emitted before the tool is
    /// dispatched so the UI can render a "calling X…" affordance. Pairs
    /// with a [`Self::ToolResult`] keyed by the same `tool_call_id`.
    ///
    /// `args` is the raw JSON the provider produced — schema validation
    /// happens in the registry. Keeping it as `serde_json::Value` here
    /// means the wire vocab doesn't drift when tool arg shapes evolve.
    ToolCall {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        #[serde(rename = "toolCallId")]
        tool_call_id: String,
        #[serde(rename = "toolName")]
        tool_name: String,
        args: serde_json::Value,
    },
    /// Result of a tool the registry just executed. Paired with the
    /// matching [`Self::ToolCall`] by `tool_call_id`. `ok` distinguishes
    /// "ran cleanly" from "the registry returned an error" — both go
    /// back to the provider as the next-turn input, but the UI renders
    /// them differently (success → Read/Grep/Edit body; failure → toast
    /// + error block).
    ToolResult {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        #[serde(rename = "toolCallId")]
        tool_call_id: String,
        ok: bool,
        /// Tool-specific payload, serialized as JSON. Read tools tend
        /// to emit `{ "content": "…", … }`; structured results (KG
        /// node, grep hits) emit their natural shape. Renderers
        /// dispatch by the matching `tool_call`'s name.
        result: serde_json::Value,
    },
    /// Write tool needs user approval before it runs (R031-F5). The
    /// renderer surfaces an inline approval row in the chat pane and
    /// posts the user's choice back via `agent_approval_decide`. The
    /// gate awaits that response before dispatching the tool — no
    /// `ToolCall` / `ToolResult` is emitted until/unless the user
    /// chooses Apply or AlwaysAllow.
    ///
    /// `args` is the raw JSON the provider produced; `bash` is the
    /// pre-parsed [`crate::agent::ApprovalRequest`]-shaped form when the
    /// call is the bash tool, so the renderer shows env / cmd / args
    /// rather than the raw input string. `requestId` is the opaque key
    /// used to resolve the prompt.
    ApprovalRequested {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        #[serde(rename = "requestId")]
        request_id: String,
        #[serde(rename = "toolName")]
        tool_name: String,
        args: serde_json::Value,
        /// `Some` for the bash tool — carries the parsed
        /// `{ env, cmd, args[] }` so the UI can render a structured
        /// approval row and pre-fill an "always allow this pattern"
        /// rule. `None` for every other tool.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        bash: Option<serde_json::Value>,
    },
    /// User resolved a pending approval. Mostly informational — the
    /// gate reacts internally; this variant lets the renderer remove
    /// the inline approval row when the user clicks a button on a
    /// different pane (or via a global "approve all" affordance).
    ///
    /// `decision` is one of `"apply"`, `"skip"`, `"always-allow"`
    /// (matches `ApprovalChoice`'s serde tag). The actual rule (if
    /// any) is the renderer's concern — this variant just signals
    /// "the prompt at `request_id` is no longer pending".
    ApprovalResolved {
        #[serde(rename = "sessionId")]
        session_id: SessionId,
        #[serde(rename = "requestId")]
        request_id: String,
        decision: String,
    },
}

impl AgentEvent {
    pub fn session_id(&self) -> &SessionId {
        match self {
            Self::SessionStarted { session_id, .. }
            | Self::TurnStarted { session_id }
            | Self::MessageDelta { session_id, .. }
            | Self::TurnEnded { session_id, .. }
            | Self::TurnFailed { session_id, .. }
            | Self::SessionEnded { session_id }
            | Self::Error { session_id, .. }
            | Self::ToolCall { session_id, .. }
            | Self::ToolResult { session_id, .. }
            | Self::ApprovalRequested { session_id, .. }
            | Self::ApprovalResolved { session_id, .. } => session_id,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_delta_serializes_with_snake_case_tag_and_camel_case_session_id() {
        let ev = AgentEvent::MessageDelta {
            session_id: SessionId::new("session:deadbeef"),
            text: "hi".into(),
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(json.contains("\"kind\":\"message_delta\""), "{json}");
        assert!(json.contains("\"sessionId\":\"session:deadbeef\""), "{json}");
    }

    #[test]
    fn turn_ended_omits_stop_reason_when_none() {
        let ev = AgentEvent::TurnEnded {
            session_id: SessionId::new("session:abcd1234"),
            text: "done".into(),
            stop_reason: None,
            usage: None,
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(!json.contains("stopReason"), "{json}");
    }

    #[test]
    fn turn_ended_includes_stop_reason_when_some() {
        let ev = AgentEvent::TurnEnded {
            session_id: SessionId::new("session:abcd1234"),
            text: "done".into(),
            stop_reason: Some("end_turn".into()),
            usage: None,
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(json.contains("\"stopReason\":\"end_turn\""), "{json}");
    }

    #[test]
    fn agent_event_session_id_extracts_for_every_variant() {
        let s = SessionId::new("session:01234567");
        let variants = [
            AgentEvent::SessionStarted {
                session_id: s.clone(),
                ticket_id: "R028-F3".into(),
                engine: "claude:opus-4-7".into(),
                cache_key: "0".into(),
                estimated_tokens: 0,
                ring_depth: 0.0,
            },
            AgentEvent::TurnStarted {
                session_id: s.clone(),
            },
            AgentEvent::MessageDelta {
                session_id: s.clone(),
                text: "x".into(),
            },
            AgentEvent::TurnEnded {
                session_id: s.clone(),
                text: "x".into(),
                stop_reason: None,
                usage: None,
            },
            AgentEvent::SessionEnded {
                session_id: s.clone(),
            },
            AgentEvent::Error {
                session_id: s.clone(),
                message: "boom".into(),
            },
            AgentEvent::ToolCall {
                session_id: s.clone(),
                tool_call_id: "tc:1".into(),
                tool_name: "read_file".into(),
                args: serde_json::json!({ "path": "Cargo.toml" }),
            },
            AgentEvent::ToolResult {
                session_id: s.clone(),
                tool_call_id: "tc:1".into(),
                ok: true,
                result: serde_json::json!({ "content": "[package]\n…" }),
            },
        ];
        for v in &variants {
            assert_eq!(v.session_id(), &s, "{v:?}");
        }
    }

    #[test]
    fn tool_call_serializes_with_camel_case_fields() {
        let ev = AgentEvent::ToolCall {
            session_id: SessionId::new("session:abcd1234"),
            tool_call_id: "tc:42".into(),
            tool_name: "read_file".into(),
            args: serde_json::json!({ "path": "Cargo.toml" }),
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(json.contains("\"kind\":\"tool_call\""), "{json}");
        assert!(json.contains("\"toolCallId\":\"tc:42\""), "{json}");
        assert!(json.contains("\"toolName\":\"read_file\""), "{json}");
        assert!(json.contains("\"path\":\"Cargo.toml\""), "{json}");
    }

    #[test]
    fn tool_result_serializes_with_ok_and_result_payload() {
        let ev = AgentEvent::ToolResult {
            session_id: SessionId::new("session:abcd1234"),
            tool_call_id: "tc:42".into(),
            ok: true,
            result: serde_json::json!({ "content": "ok" }),
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(json.contains("\"kind\":\"tool_result\""), "{json}");
        assert!(json.contains("\"ok\":true"), "{json}");
        assert!(json.contains("\"content\":\"ok\""), "{json}");
    }
}
