//! @arch:layer(kg_store)
//! @arch:role(bridge)
//!
//! Pinned wire constants for the Anthropic `/v1/messages` OAuth path
//! (the `crab` / HAo preset). Loaded once at boot from a build-time
//! audit artifact, then read by [`crate::agent::AnthropicAuth::Oauth`]
//! to replay Claude Code's signature on every request.
//!
//! See `architecture/yah-claude-shape-capture.md` for the full design,
//! including the build-time audit step that regenerates the embedded
//! TOML against a bundled `claude` binary. Until R028-F8 lands the
//! bundled claude, [`BASELINE_TOML`] holds the public-known constants
//! only and the `x-stainless-*` / `user-agent` headers stay unset.

use std::collections::HashMap;
use std::sync::{Arc, OnceLock};

use serde::Deserialize;

/// TOML embedded into the binary at build time. When the audit step
/// (deferred — see [yah-claude-shape-capture.md] "Out of scope") lands,
/// this swap-in becomes the only place that needs to change to ship a
/// new pinned signature.
const BASELINE_TOML: &str = include_str!("../resources/claude-shape-baseline.toml");

/// Process-wide handle to the loaded shape. `None` means the
/// `BASELINE_TOML` failed to parse (degraded mode — `crab` falls back
/// to its hardcoded constants and logs a warning at boot). `Some(None)`
/// is impossible: the outer `Some` means "init ran".
static PINNED_SHAPE: OnceLock<Option<Arc<PinnedShape>>> = OnceLock::new();

/// Static wire-shape values that make `crab`'s `/v1/messages` requests
/// match Claude Code's signature. Loaded from a build-time audit
/// artifact (today: hand-written baseline; later: regenerated by an
/// audit binary that scans the bundled `claude` source).
#[derive(Debug, Clone)]
pub struct PinnedShape {
    pub claude_version: String,
    pub audited_at: String,
    /// Header name → value. Names compared case-insensitively at apply
    /// time; the `apply()` skip-list (authorization, host,
    /// content-length) prevents conflict with reqwest's own bookkeeping.
    pub headers: HashMap<String, String>,
    /// First system block on OAuth-authed requests. Anthropic enforces
    /// the prefix as the TOS hook that distinguishes Claude Code from
    /// third-party tools.
    pub system_prefix: String,
    pub system_block_count: usize,
    pub system_cache_control: bool,
    /// Top-level body fields the wire enforces beyond what we already
    /// set (today: `stream = true`, which we already send). Reserved
    /// for the audit step to populate.
    #[allow(dead_code)]
    pub body_extras: HashMap<String, serde_json::Value>,
}

#[derive(Debug, thiserror::Error)]
pub enum LoadError {
    #[error("pinned shape malformed: {0}")]
    Malformed(#[from] toml::de::Error),
}

#[derive(Debug, Deserialize)]
struct ShapeFile {
    claude_version: String,
    audited_at: String,
    #[serde(default)]
    headers: HashMap<String, String>,
    #[serde(default)]
    system: SystemSection,
    #[serde(default)]
    body: HashMap<String, toml::Value>,
}

#[derive(Debug, Deserialize)]
struct SystemSection {
    #[serde(default)]
    prefix: String,
    #[serde(default = "default_block_count")]
    block_count: usize,
    #[serde(default = "default_cache_control")]
    cache_control: bool,
}

impl Default for SystemSection {
    // Manual impl so a TOML missing the `[system]` table entirely still
    // gets the per-field defaults (block_count = 2, cache_control =
    // true) rather than the derived `usize::default()` / `bool::default()`
    // values, which would silently produce an empty single-block prelude.
    fn default() -> Self {
        Self {
            prefix: String::new(),
            block_count: default_block_count(),
            cache_control: default_cache_control(),
        }
    }
}

fn default_block_count() -> usize {
    2
}
fn default_cache_control() -> bool {
    true
}

/// Parse pinned-shape TOML into a [`PinnedShape`]. Used by [`init`]
/// at boot; exposed so tests can round-trip a fixture without touching
/// the global.
pub fn parse(src: &str) -> Result<PinnedShape, LoadError> {
    let file: ShapeFile = toml::from_str(src)?;
    let body_extras = file
        .body
        .into_iter()
        .map(|(k, v)| (k, toml_value_to_json(v)))
        .collect();
    Ok(PinnedShape {
        claude_version: file.claude_version,
        audited_at: file.audited_at,
        headers: file.headers,
        system_prefix: file.system.prefix,
        system_block_count: file.system.block_count,
        system_cache_control: file.system.cache_control,
        body_extras,
    })
}

/// Load [`BASELINE_TOML`] into the global registry. Idempotent — calling
/// twice is a no-op (subsequent inits are dropped). Failure leaves the
/// global as `None` so OAuth requests fall back to their hardcoded
/// degraded path.
pub fn init() {
    PINNED_SHAPE.get_or_init(|| match parse(BASELINE_TOML) {
        Ok(shape) => {
            tracing::info!(
                claude_version = %shape.claude_version,
                audited_at = %shape.audited_at,
                header_count = shape.headers.len(),
                "claude shape: pinned constants loaded",
            );
            Some(Arc::new(shape))
        }
        Err(err) => {
            tracing::warn!(
                error = %err,
                "claude shape: BASELINE_TOML failed to parse — `crab` (HAo) will run degraded",
            );
            None
        }
    });
}

/// Read the loaded shape, if any. Returns `None` when [`init`] hasn't
/// run yet *or* when parsing failed.
pub fn pinned() -> Option<Arc<PinnedShape>> {
    PINNED_SHAPE.get().and_then(|opt| opt.clone())
}

/// Best-effort `toml::Value → serde_json::Value`. Used only for
/// `body_extras` — TOML's full type set is a superset of JSON's
/// (datetimes, etc), but body fields claude sends are JSON-shaped
/// today; if a future audit needs richer types this widens.
fn toml_value_to_json(v: toml::Value) -> serde_json::Value {
    use toml::Value;
    match v {
        Value::String(s) => serde_json::Value::String(s),
        Value::Integer(i) => serde_json::Value::from(i),
        Value::Float(f) => serde_json::json!(f),
        Value::Boolean(b) => serde_json::Value::Bool(b),
        Value::Datetime(dt) => serde_json::Value::String(dt.to_string()),
        Value::Array(arr) => {
            serde_json::Value::Array(arr.into_iter().map(toml_value_to_json).collect())
        }
        Value::Table(tbl) => serde_json::Value::Object(
            tbl.into_iter()
                .map(|(k, v)| (k, toml_value_to_json(v)))
                .collect(),
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baseline_toml_parses_with_expected_constants() {
        let shape = parse(BASELINE_TOML).expect("baseline TOML must parse");
        assert_eq!(
            shape.headers.get("anthropic-beta").map(String::as_str),
            Some("oauth-2025-04-20,claude-code-20250219"),
        );
        assert_eq!(
            shape.headers.get("anthropic-version").map(String::as_str),
            Some("2023-06-01"),
        );
        assert!(
            shape
                .system_prefix
                .starts_with("You are Claude Code"),
            "system prefix is the TOS-enforced Claude Code identity",
        );
        assert_eq!(shape.system_block_count, 2);
        assert!(shape.system_cache_control);
    }

    #[test]
    fn parse_rejects_malformed_toml() {
        let bad = "claude_version = \"x\"\nthis is not toml ===";
        assert!(parse(bad).is_err());
    }

    #[test]
    fn parse_accepts_minimal_shape_with_defaults() {
        let src = r#"
            claude_version = "test"
            audited_at = "2026-04-29T00:00:00Z"
        "#;
        let shape = parse(src).expect("minimal shape must parse via field defaults");
        assert!(shape.headers.is_empty());
        assert_eq!(shape.system_block_count, 2);
        assert!(shape.system_cache_control);
        assert_eq!(shape.system_prefix, "");
    }
}
